version: '3.3'

services:
  apache:
    image:
      build: ./apache
      ports:
        - 80:80 
      restart: always
      networks:
        - frontend_network:
        - backend_network:
      depends_on:
        - mysql
      volumes:
        - ./iaw-practica-lamp/src:/var/www/html	

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./iaw-practica-lamp/db:/docker-entrypoint-initdb.d
    networks:
      - backend_network
    security_opt:
      - seccomp:unconfined

  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      - frontend_network

volumes:
  mysql_data:

networks:
  frontend_network:
  backend_network:
