FROM ubuntu:21.04

LABEL AUTHOR="Manuel Crisol Belver"

ENV DEBIAN_FRONTEND nointeractive

RUN apt update && \
    apt install -y apache2 && \
    apt install -y php && \
    apt install -y libapache2-mod-php && \
    apt install -y php-mysql && \
    rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]